# Generated by Django 5.0.8 on 2024-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_id', models.CharField(max_length=255)),
                ('study', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('in_out_patient', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('phenotype', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('amoxycillin_clavulanate', models.CharField(blank=True, max_length=50, null=True)),
                ('amoxycillin_clavulanate_I', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
